local_backend: true

backend:
  name: git-gateway
  branch: master

locale: ru

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: articles
    label: Статьи
    label_singular: Статья
    folder: src/content/articles
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Заголовок
        name: title
        widget: string

      - label: Краткое описание
        name: description
        widget: text

      - label: Обложка
        name: cover
        widget: image
        required: false
        choose_url: false

      - label: Описание изображения
        name: cover_alt
        widget: string
        required: false
        hint: Кратко опишите, что изображено на обложке.

      - label: PDF-файл статьи
        name: pdf
        widget: file
        required: false
        choose_url: false
        hint: Загрузите документ в формате PDF.

      - label: Текст статьи
        name: body
        widget: markdown
  - name: conferences
    label: Конференции
    label_singular: Конференция
    folder: src/content/conferences
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Название конференции
        name: title
        widget: string

      - label: Краткое описание
        name: description
        widget: text

      - label: Обложка
        name: cover
        widget: image
        required: false
        choose_url: false

      - label: Описание изображения
        name: cover_alt
        widget: string
        required: false

      - label: Программа или материалы в PDF
        name: pdf
        widget: file
        required: false
        choose_url: false

      - label: Текст
        name: body
        widget: markdown
  